### ISSUE TITLE
combobox freezes HypeDyn on Windows 10 with touchscreen

### ISSUE THREAD

**Issue by lexaay** [narrativeandplay/hypedyn2#115]
Clicking a combobox in the Node Editor freezes the entire app. Reported on Windows 10 with touchscreen.

![hypedynerror1](https://cloud.githubusercontent.com/assets/3497492/22234371/9c9cfaa6-e232-11e6-95dd-86021bb7cbd0.JPG)

Seems to be this bug: [https://bugs.openjdk.java.net/browse/JDK-8136726](https://bugs.openjdk.java.net/browse/JDK-8136726)

As the bug has been fixed, we should look into what version of Java we are compiling with and see if there's an easy fix.

Also there is a workaround: 
[http://stackoverflow.com/questions/31786980/javafx-windows-10-combobox-error](http://stackoverflow.com/questions/31786980/javafx-windows-10-combobox-error)

**Comment by benedictleejh** [comment]
The fix for JDK-8132897 (referenced in the StackOverflow issue) seems to have been backported to earlier JDK versions (8u66, 8u71, and 8u72). Can we get someone to compile using the latest JDK and see if the bug pops up?

The packaging process bundles a JRE, if I recall, but again, this needs checking. A bundled JRE would give us control over the Java version HypeDyn 2 executes with, and be less of a hassle than dealing with various JRE versions people might have installed.

**Comment by lexaay** [comment]
Work-around:
1.     Right-click HypeDyn 2.exe
2.     Select Properties. The properties window should pop up.
3.     Select the Compatibility tab
4.     Check the "Run this program in compatibility mode for:" checkbox.
5.     Select "Windows Vista (Service Pack 2)"
6.     Click OK

I assume this works because it disables touchscreen support. :)

**Comment by lexaay** [comment]
Yes, I believe the JRE corresponding to the JDK in the path at compile time is bundled with the application. I'll try compiling with the latest JDK on Windows and see if it solves the problem.

Alex

**Comment by lexaay** [comment]
Seems to be fixed by compiling and bundling with latest java. Note that gradle seems to bundle the jdk pointed to by JAVA_HOME.
