### ISSUE TITLE
Fragment at the end of line gets deleted when pressing enter to create new line

### ISSUE THREAD

**Issue by barefists** [narrativeandplay/hypedyn2#128]
If you have a fragment at the end of a line in the editor, trying to create a new line under it by pressing "Enter" while cursor is at the end of that line will remove the fragment instead.

**Comment by lexaay** [comment]
Can you provide more specific details as to where the insertion point/selection is when the fragment is deleted? If you click anywhere on the fragment the editor tends to select the entire fragment, at which point pressing enter will probably remove the fragment. However, if you use the arrow keys to move the insertion point to the end of the line immediately after the fragment (rather than clicking with the mouse), the new line should be added correctly.

**Comment by barefists** [comment]
I use the arrow keys to attempt to reach the end of the line, but as the typing cursor pass by the fragment, it gets highlighted. Pressing right arrow at that point does nothing, the fragment continues to be highlighted. So when I press enter at that point to create the newline, the fragment gets deleted.

**Comment by lexaay** [comment]
What platform is this on, Mac or Windows?

**Comment by barefists** [comment]
Windows.

**Comment by benedictleejh** [comment]
I can't replicate this on Windows on the latest development, the arrow keys work as expected, and pressing right once the fragment is highlighted does un-highlight the fragment, and allow you to keep typing.

However, note that a newline inserted this way is part of the last fragment.

**Comment by lexaay** [comment]
Seems to have been fixed when we upgraded to RichTextFX 0.7-M5, can't be reproduced on latest development.
