### ISSUE TITLE
allow zooming out further?

### ISSUE THREAD

**Issue by lexaay** [narrativeandplay/hypedyn2#85]
With a mid-size (20+ nodes) story, even when zooming out all the way, I can't see the entire story. We could 1) allow zooming out further (although the question then is how to handle display of the content text and node name), and/or 2) add a "mini-map.

**Comment by benedictleejh** [comment]
Allowing further zooming out really isn't much of a problem, because it's just changing a single constant. The display could admittedly be more of an issue, depending on how much zoom out is applied. The code will automatically handle cutting of the text of the nodes and node names, but at some point, that's going to end up being a single letter or less (with ellipses) if too much zoom out is applied.

Adding a minimap could work, but then depending on the size of the map, and how much is to be shown, you might not be able to have any text on the shown nodes anyway.

**Comment by lexaay** [comment]
I'd suggest that beyond a certain threshold (probably the current zoom limit) the text not be shown, just the node outlines. This is what Twine does, and it seems to work.
